# File: netlify.toml

[build]
  # Comando per costruire la tua app React
  command = "npm run build"
  # Cartella dove si trova il sito costruito
  publish = "build"
  # Cartella dove si trovano le tue funzioni serverless
  functions = "netlify/functions"

[dev]
  # Porta per l'ambiente di sviluppo locale
  port = 8888
